import type { Metadata } from "next";
import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <header className={styles.header}>Japan Cities Overview</header>
        {children}
        <footer className={styles.footer}>
          © 2024 <a href="https://github.com/Taru-source">Taru-source</a>
        </footer>
      </body>
    </html>
  );
}
