name: Scheduled URL Access

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  curl-job:
    runs-on: ubuntu-latest

    steps:
      - name: Curl the URL
        run: curl -I https://japan-cities-overview.vercel.app/
