name: Scheduled URL Access

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  curl-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Curl the URL
        run: curl -I https://japan-cities-overview.vercel.app/
